name: NestJS CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Clone Repo
        run: git clone https://github.com/sharqX/Task-17-6-24.git

      - name: Build Image
      - run: docker build -t thesharqx/nestjs-app .

      - name: Navigate to directory
        run: cd Task-17-6-24.git

      - name: Run App
        run: docker run -d -p 80:3000 thesharqx/nestjs-app
