name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Clone Repository
        run: git clone https://github.com/sharqX/Task-17-6-24.git

      - name: Navigate to directory
        run: cd Task-17-6-24

      - name: Install dependencies
        run: npm install

      - name: Run App
        run: npm run start
